### ISSUE TITLE
Would you consider using a different License?

### ISSUE THREAD

**Issue by OscarAbraham** [prime31/Unity-Ripgrep-Search-Tool#1]
Hi. Thanks for sharing this project. I think it's very interesting and certainly useful.

The Unlicense has several problems that can make projects under it difficult to use. Some companies and public institutions don't allow code with that license. It's generally deemed badly written from a legal perspective. For example, there's a contradiction between the Public Domain dedication, which implies no obligations, and the warranty disclaimer at the end. The name itself is kind of bad, as _to unlicense_ means to remove the rights given to others. Also, the URL given at the end, https://unlicense.org, doesn't work anymore.

Here are some links with more info in case you're interested: 
- [What is wrong with the Unlicense in StackExchange](https://softwareengineering.stackexchange.com/questions/147111/what-is-wrong-with-the-unlicense)
- [A review of the license in a mailing list from opensource.org](https://lists.opensource.org/pipermail/license-review_lists.opensource.org/2012-January/001386.html)
- [A Hacker News thread](https://news.ycombinator.com/item?id=30554087) that originated from [this blog post](https://chrismorgan.info/blog/unlicense/).

I love the Public Domain dedication from an idealistic perspective, but the real world makes it unrealistic. People often point out to [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/) as a better alternative for Public Domain dedication, but that license is still problematic for software, as it explicitly doesn't waive any patent rights required to use the software.

I suggest using the [0BSD license](https://opensource.org/license/0bsd/), at least as an alternative license if you don't want to remove the Unlicense. It has all the same practical implications (do whatever you want, no attribution required, warranty disclaimer), it just doesn't have the Public Domain dedication that, at this point, is a purely ideological matter.

Thanks again :).
Regards,
Oscar Abraham.

**Comment by prime31** [comment]
PR any permissible license you want. I don’t mind changing it at all.
